### ISSUE TITLE
Clipboard support for Wayland/other X clipboard programms

### ISSUE THREAD

**Issue by lukeflo** [Multirious/zsh-helix-mode#2]
At the moment, your handling of the system clipboard seems hardcoded to `xclip` which is not the default for many Linux distros and Wayland as compositor:

https://github.com/Multirious/zsh-helix-mode/blob/457f47e1ba1c9a22913d7bb2c86aa2e3bcfa0769/zsh-helix-mode.plugin.zsh#L14

Maybe there is a more flexible solution to set the command for system clipboard access.

**Comment by Multirious** [comment]
This shouldn't be hardcoded and is intended to be configurable. Seems like I've missed something here.

**Comment by Multirious** [comment]
Ah, seems like I have to export the variables

**Comment by lukeflo** [comment]
In my case, running `wayland`, if I change the commands manually to `wl-copy` and `wl-paste --no-newline` it works flawlessly.

I don't know if there is an idiomatic way to check the available clipboard commands. At least, you could implement a custom check, looking for `DISPLAY` (for X) or `WAYLAND-DISPLAY` env vars to get the window system/compositors.

Something like (maybe with additional command checks):

```bash
if [[ -n $DISPLAY ]]; then
    ZHM_CLIPBOARD_PIPE_CONTENT_TO="xclip -sel clip"
    ZHM_CLIPBOARD_READ_CONTENT_FROM="xclip -o -sel clip"
elseif [[ -n $WAYLAND_DISPLAY ]]; then
    ZHM_CLIPBOARD_PIPE_CONTENT_TO="wl-copy"
    ZHM_CLIPBOARD_READ_CONTENT_FROM="wl-paste --no-newline"
else
    # some default code
fi
```
